package pe.nasqa.values.control;

public enum CEPerfil {
	DI_ADMIN,
	DI_CONSULTAS,
	DI_REPORTES,
	DI_COORDINACION,
	DI_COORDINACION_TELEF,
	DI_OPERADOR,
	CL_ADMIN,
	CL_CONSULTAS,
	CL_REPORTES,
	CL_COORDINACION,
	CL_COORDINACION_TELEF
}
